In [13]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
output = np.where(arr%2!=0,-1,arr)
output

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [12]:
arr = np.arange(10)
output = np.reshape(arr,(2,5))
output

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
arr = np.array([1,2,3])
output1 = np.repeat(arr,3)
output2 = np.tile(arr,3)
output = np.concatenate((output1 , output2),axis=0)
output

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
arr1 = np.array([1,2,3,2,3,4,3,4,5,6])
arr2 = np.array([7,2,10,2,7,4,9,4,9,8])
output = np.intersect1d(arr1,arr2)
output

array([2, 4])

In [25]:
arr1 = np.array([1,2,3,2,3,4,3,4,5,6])
arr2 = np.array([7,2,10,2,7,4,9,4,9,8])
output = np.where(arr1 == arr2)
output

(array([1, 3, 5, 7]),)

In [29]:
output = np.random.uniform(5, 10, size=(5, 3))
output

array([[6.28295469, 5.36941749, 5.85950004],
       [6.90989424, 8.63864588, 5.91823874],
       [5.42782712, 6.45627786, 9.41116466],
       [6.60643593, 7.93124879, 7.34533791],
       [6.87798647, 9.08737581, 9.4854389 ]])

In [32]:
output = np.arange(15)
np.set_printoptions(threshold=6)
output 

array([ 0,  1,  2, ..., 12, 13, 14])

In [36]:
np.random.seed(100)
arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)
arr 

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

In [46]:
arr = np.arange(4).reshape(2,2)
arr[:,[0,1]] = arr[:,[1,0]]
arr 

array([[1, 0],
       [3, 2]])

In [47]:
arr = np.arange(4).reshape(2,2)
arr[[0,1]] = arr[[1,0]]
arr

array([[2, 3],
       [0, 1]])